model:
  backbone:
    _target_: src.models.backbone.MLPBackbone
    num_cells:
    - 256
    - 256
    activation: tanh
    in_keys:
    - - observation
      - globals
    - - observation
      - select_cats
    - - observation
      - context_card_ids
    - - observation
      - stadium_id
    - - observation
      - options
    - - observation
      - pokemon
    - - observation
      - my
    - - observation
      - opp
    - - observation
      - select_deck
    - - observation
      - looking
  head:
    _target_: src.models.heads.LinearPolicyHead
  embed_dim: 128
  value_head:
    num_cells:
    - 256
    - 256
  adapter:
    card_embed_dim: 8
    attack_embed_dim: 8
    category_embed_dim: 4
max_options: 96
encoder: structured
